version: '3.8'

services:
  school-page-management-service:
    build: ./SchoolPageManagementService
    container_name: school-page-management
    ports:
      - "8080:8080"
    networks:
      - myNetwork
    depends_on:
      - kafka
      - zookeeper
      - mysql
      - mongodb

  school-news-publishing-service:
    build: ./SchoolNewsPublishingService
    container_name: news-publishing
    ports:
      - "8081:8081"
    networks:
      - myNetwork
    depends_on:
      - kafka
      - zookeeper
      - mysql
      - mongodb

  student-subscription-service:
    build: ./StudentSubscriptionService
    container_name: student-subscription
    ports:
      - "8082:8082"
    networks:
      - myNetwork
    depends_on:
      - kafka
      - zookeeper
      - mysql
      - mongodb

  newsfeed-service:
    build: ./newsfeed-service
    container_name: newsfeed
    ports:
      - "3000:3000"
    networks:
      - myNetwork
    depends_on:
      - kafka
      - zookeeper
      - mysql
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: classting-mongodb
    ports:
      - "27017:27017"
    networks:
      - myNetwork
    
  mysql:
    image: mysql:8.0
    container_name: classting-mysqldb
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=admin1234
      - MYSQL_DATABASE=news_feed
    networks:
      - myNetwork

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "32181:32181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - myNetwork

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-msa
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:32181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 4
    networks:
      - myNetwork

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - "8989:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:29092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:32181
    networks:
      - myNetwork

networks:
  myNetwork:
    driver: bridge
