server:
  port: 8081

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: news
      auto-index-creation: true

  jpa:
    open-in-view: false

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

external:
  school-page-management-service:
    host: http://localhost:8080
